[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
methods = { path = "../methods" }
risc0-zkvm = "0.12"
bytemuck = "1.7"
bonsai-sdk = { version = "0.7" }
hex = "0.4"
serde = "1.0"
apiverifier = { path = "../core"}